### ISSUE TITLE
About text pre-processing ordering

### ISSUE THREAD

**Issue by yredwood** [ttaoREtw/Tacotron-pytorch#6]
def txt2seq(txt):
    txt = ''.join([t for t in txt if t in _characters])
    txt = english_cleaners(txt) + _eos
    seq = [symbol2id[s] for s in txt]
    return seq

I guess 'english_cleaners' function should be called ahead because first line erases numbers.

**Comment by ttaoREtw** [comment]
You are right! 
I will fix this and push it later.
