### ISSUE TITLE
模型的输入问题

### ISSUE THREAD

**Issue by uyplayer** [ttaoREtw/Tacotron-pytorch#9]
模型的输入是 Word Embedding 还是 Character Embedding ？  。 “TACOTRON: TOWARDS END-TO-END SPEECH SYN- THESIS” 论文里面输入的 Character Embedding  。 我大概看了一下代码好像找不到关于Character Embedding 的部分

**Comment by ttaoREtw** [comment]
Please check these
1. text to symbol: https://github.com/ttaoREtw/Tacotron-pytorch/blob/master/src/symbols.py#L12
2. symbol to embedding: https://github.com/ttaoREtw/Tacotron-pytorch/blob/master/src/module.py#L288

**Comment by uyplayer** [comment]
谢谢你
